# site properties and page defaults
title: ENHANCE Lab
subtitle: 
description: I lead the Equity iN Health And Non-Coding Elements (ENHANCE) lab. The ENHANCE lab research projects aim to assign function to genetic variants that are associated with health and disease using bioinformatics, zebrafish and cell assays. We work with Māori and Pacific genetic data to identify clinically-relevant genetic variants that are unique to Māori and Pacific people and we focus on conditions that affect women and are underrepresented in the research space. The long-term outcomes of our work has the potential to reduce health disparities and improve genetic equity in these underrepresented groups.
header: images/JAZF1_rostral.jpg
footer: images/JAZF1_caudal.jpg
header-dark: true
footer-dark: true
proofer: false

# site social media and other links
links:
  email: megan.leask@otago.ac.nz
  orcid: 0000-0003-3199-5277
  google-scholar: AvfnEL4AAAAJ
  github: https://github.com/ENHANCELABNZ
  twitter: https://x.com/leaskmegan

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts
  - sitemap.xml

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
  - _members/tem_plate.md
